### ISSUE TITLE
[mic step1] Overview

### ISSUE THREAD

**Issue by sirspock** [mintproject/mic#131]
## Pipeline

1. **The user must go to the directory where the code is.**
  The directory must contain the data.
We don't support data outside this directory

2. **The user must type**
```
mic encapsulate step1 <path_to_user_execution_directory>
```

4. _MIC detect the framework/language (we support python and conda)_
MIC prints
```
Success/Failed
```
5. _MIC renders the docker file and dependencies in the MIC component directory._
6. _MIC build the docker image_
7. _MIC run the image:_

8. _The user sees the message:_
```
You are in a Linux environment Debian distribution
We detect the following dependencies.

- If you install new dependencies using `apt` or `apt-get`, remember to add them in Dockerfile
- If you install new dependencies using conda, MIC is going to detect them
- If you install new dependencies using python, MIC is going to detect them

Please run your model.
```

3. _MIC create a new directory in the MIC component directory with the data, src, mic.yaml_

Issues:

- [ ] ~~MIC creates a directory to store the components: `$HOME/mic`~~ 
- [x] MIC step 1 must expect argument: `path_to_user_execution_directory`~~  and two prompts question: name and description~~ 
- [ ] ~~MIC creates a new directory in the MIC component directory using the name~~ 
- [x] MIC detect python dependencies
- [ ] MIC detect conda dependencies
- [x] MIC build the image
- [x] MIC run the image: 
  1. Interactive mode, tty mode
  2. Mount -v <MICcomponentdirectory>:/tmp and <mic_component_directory>:$HOME
- [x] Add welcome message using click

**Comment by dgarijo** [comment]
I like the direction where this is going, but I have some questions:

- Where is the mic component created? I think we should point to the path of where the code/data is, but the user should know that they are creating a mic component in a different path. It's like selecting the project (mic component) path/name.
- What happens if users have data in different path than code?
- This workflow does not capture the selection of inputs and parameters. Is this a later step?
