### ISSUE TITLE
Author is registered as "blank node"

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#54]
**mic version**
0.2.0

**Describe the bug**
After successfully saving an author, it gets registered as a blank node online. Example: https://rdfexplorer.mint.isi.edu/page/okn/i/mint/123a8b93-da18-44d3-8ef3-8b5b39566652

There seems to be an issue registering new ids for resources.

**Comment by maurya-rohit** [comment]
@dgarijo Is this issue only with the registering new Author or is it for any new resource? I feel it is only for the Authors ?

**Comment by dgarijo** [comment]
Last time I tried it was only for authors.

**Comment by maurya-rohit** [comment]
I tried figuring out the behaviour. Actually the issue is model catalog is not able to recognize the author as a separate entity and hence the edges is not created in the graph from the entity. Although if you see the data of author is there but the person node is missing from the graph.
![image](https://user-images.githubusercontent.com/11644927/81517795-ddd8ca00-92f0-11ea-8ad7-e5106aa87d37.png)
We might have to fix this in model catalog api as author is List[Object] which should be a proper entity.
